---

- name: Playbook to install Automation Agent
  hosts: all
  become: true
  vars_prompt:
    - name: run_preflight
      prompt: "Install/Update OpenSSL? (N = no, Y = yes)"
      default: "N"

  roles:
    - { role: preflight, when: run_preflight == "Y" or run_preflight == "y" }
    - { role: install }

  vars:
    ## Automation Agent file path
    automation_agent_pkg: http://phelmondbbi001.karmalab.net:8080/download/agent/automation/mongodb-mms-automation-agent-manager-latest.x86_64.rpm

    ## Automation Agent configuration (required)
    mms_group_id:       "5b3e84d0a6030a0dc295428f"
    mms_api_key:        "5b3e84ffa6030a0dc2956fe140ec96719a235aa458961b5997e07805"
    mms_base_url:       "http://phelmondbbi001.karmalab.net:8080"

    ## Automation Agent configuration (optional)
    mms_config_backup:  "/var/lib/mongodb-mms-automation/mms-cluster-config-backup.json"
    log_file:           "/var/log/mongodb-mms-automation/automation-agent.log"
    log_level:          "INFO"
    max_log_files:      10
    max_log_file_size:  268435456
