---
- name: Download automation agent
  command: curl -OL "{{ automation_agent_path }}/{{ automation_agent_filename }}"

- name: Install automation agent
  command: sudo rpm -U {{ automation_agent_filename }}

- name: Configure automation agent
  template: src=automation-agent.config.j2 dest=/etc/mongodb-mms/automation-agent.config

- name: Start automation agent
  service: name=mongodb-mms-automation-agent state=started
